# Generated by Django 6.0.6 on 2026-06-11 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announce',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='announce',
            name='district',
            field=models.CharField(choices=[('Tamdja', 'Tamdja'), ('Djeleng', 'Djeleng'), ('SOCADA', 'SOCADA'), ('Mairie rural', 'Mairie rurale'), ('Kamkop', 'Kamkop'), ('Banengo', 'Banengo'), ('Bafoussam', 'Bafoussam'), ('TPO', 'TPO')], max_length=50),
        ),
    ]
